#[repr(u32)]
#[derive(Debug, Clone, Copy)]
pub enum CallbackType {
    Default = 0,
    Get = 1,
    Store = 2,
    Counter = 3,
    Touch = 4,
    Remove = 5,
    Unlock = 6,
    Stats = 7,
    Versions = 8,
    Verbosity = 9,
    Flush = 10,
    Observe = 11,
    GetReplica = 12,
    Endure = 13,
    Http = 14,
    Cbflush = 15,
    Obseqno = 16,
    Storedur = 17,
    Sdlookup = 18,
    Sdmutate = 19,
    Max = 20,
}
