language: rust

cache: cargo

sudo: true

rust:
  - stable
  - beta
  - nightly

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - graphviz

matrix:
  allow_failures:
    - rust: nightly

before_install:
  - ./.travis/install.sh

after_script:
  - cargo graph \
    --optional-line-style dashed \
    --optional-line-color red \
    --optional-shape box \
    --build-shape diamond \
    --build-color green \
    --build-line-color orange
