language: rust

cache: cargo

sudo: true

rust:
  - stable
  - beta
  - nightly

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - graphviz
      - upx-ucl
      - wget

matrix:
  allow_failures:
    - rust: nightly

before_script:
  - export PATH=$PATH:/home/travis/.cargo/bin

before_install:
  - ./.travis/install.sh
  - wget http://packages.couchbase.com/releases/4.1.0/couchbase-server-community_4.1.0-ubuntu12.04_amd64.deb
  - sudo dpkg -i couchbase-server-community_4.1.0-ubuntu12.04_amd64.deb
  - "curl -u username=[Administrator]&password=[Administrator] -v -X POST http://[localhost]:8091/node/controller/setupServices -d services=[data | index | query]"
  - cargo install cargo-count --force
  - cargo install cargo-graph --force
  - cargo install cargo-outdated --force

after_script:
  - make

notifications:
  email:
    - korczis@gmail.com
    - lv.bossek@gmail.com
