language: rust

cache: cargo

sudo: true

rust:
  - stable
  - beta
  - nightly

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - graphviz
      - upx-ucl

matrix:
  allow_failures:
    - rust: nightly

before_script:
  - export PATH=$PATH:/home/travis/.cargo/bin

before_install:
  - ./.travis/install.sh
  - cargo install cargo-count --force
  - cargo install cargo-outdated --force

after_script:
  - make

notifications:
  email:
    - korczis@gmail.com
    - lv.bossek@gmail.com
